"""
Goodreads Scraper — Review Counts & Shelf Frequencies
======================================================
Scrapes Goodreads for reviews, ratings, and user-applied shelves/tropes.
Input:  CSV generated by list_scraper.py
Output: CSV populated with stats and a JSON string of shelf data

Usage:
    python scrapers/goodreads_scraper.py \
        --template data/raw/epoch_2_backtest/2018_mf_template.csv \
        --output data/raw/epoch_2_backtest/2018_mf_processed.csv \
        --status-log data/logs/engine_status.log
"""

import argparse
import json
import os
import re
import time
from datetime import date, datetime, timezone

import pandas as pd
from bs4 import BeautifulSoup

from gr_http import fetch_url, make_scraper

BOOK_SHOW_RE = re.compile(r"/book/show/(\d+)")


def _utc_ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def resolve_apollo_ref(node, apollo_state):
    """Recursively follows Apollo GraphQL pointers to get the real data."""
    if isinstance(node, dict) and "__ref" in node:
        return apollo_state.get(node["__ref"], {})
    return node


def _format_review_count(reviews) -> str:
    if reviews is None:
        return "no count"
    try:
        return f"{int(reviews):,}"
    except (TypeError, ValueError):
        return str(reviews)


def book_id_from_url(url: str) -> int | None:
    if not isinstance(url, str):
        return None
    m = BOOK_SHOW_RE.search(url)
    return int(m.group(1)) if m else None


def scrape_book_page(scraper, url: str) -> dict:
    try:
        response = fetch_url(scraper, url, timeout=30)
        if response.status_code == 429:
            return {"status": "rate_limited", "reviews": None, "rating": None, "shelves": None}
        if response.status_code != 200:
            return {"status": f"error_{response.status_code}", "reviews": None, "rating": None, "shelves": None}
    except Exception:
        return {"status": "request_failed", "reviews": None, "rating": None, "shelves": None}

    soup = BeautifulSoup(response.text, "html.parser")
    next_data_script = soup.find("script", id="__NEXT_DATA__")

    if not next_data_script:
        return {"status": "no_data_blob", "reviews": None, "rating": None, "shelves": None}

    try:
        data = json.loads(next_data_script.string)
        book_data = data["props"]["pageProps"]["apolloState"]

        book_key = next((k for k in book_data.keys() if k.startswith("Book:")), None)
        if not book_key:
            return {"status": "book_key_not_found", "reviews": None, "rating": None, "shelves": None}

        book = book_data[book_key]

        # --- 1. RESOLVE STATS ---
        stats_node = resolve_apollo_ref(book.get("stats", {}), book_data)

        # If stats aren't directly on the Book, follow the pointer to the Work node
        if not stats_node or ("averageRating" not in stats_node):
            work_node = resolve_apollo_ref(book.get("work", {}), book_data)
            stats_node = resolve_apollo_ref(work_node.get("stats", {}), book_data)

        # Ultimate fallback: scan the whole graph for the stats block
        if not stats_node or ("averageRating" not in stats_node):
            for _k, v in book_data.items():
                if isinstance(v, dict) and "averageRating" in v and (
                    "textReviewsCount" in v or "ratingsCount" in v
                ):
                    stats_node = v
                    break

        rating = stats_node.get("averageRating") if stats_node else None
        reviews = stats_node.get("textReviewsCount") if stats_node else None
        if reviews is None and stats_node:
            reviews = stats_node.get("ratingsCount")

        # --- 2. RESOLVE SHELVES (Brute Force Scanner) ---
        # BookGenre objects usually live *nested* under Book.bookGenres, not as top-level
        # apollo keys. Walk the entire normalized cache. Goodreads often omits usersCount on
        # book pages; when missing we still record the genre name with JSON null.
        shelves_dict = {}

        def _walk_apollo_nested(obj):
            if isinstance(obj, dict):
                yield obj
                for v in obj.values():
                    yield from _walk_apollo_nested(v)
            elif isinstance(obj, list):
                for item in obj:
                    yield from _walk_apollo_nested(item)

        def _set_shelf(name: str, count) -> None:
            if not name:
                return
            key = name.lower()
            if count is not None:
                try:
                    shelves_dict[key] = int(count)
                except (TypeError, ValueError):
                    if key not in shelves_dict:
                        shelves_dict[key] = None
            elif key not in shelves_dict:
                shelves_dict[key] = None

        for root in book_data.values():
            for node in _walk_apollo_nested(root):
                if not isinstance(node, dict):
                    continue
                is_book_genre = node.get("__typename") == "BookGenre"
                has_genre_and_count = "genre" in node and (
                    "usersCount" in node
                    or "tagCount" in node
                    or "count" in node
                )
                if not (is_book_genre or has_genre_and_count):
                    continue

                genre_ptr = node.get("genre", {})
                genre_inner = resolve_apollo_ref(genre_ptr, book_data)
                name = (
                    genre_inner.get("name")
                    if isinstance(genre_inner, dict)
                    else None
                )

                count = (
                    node.get("usersCount")
                    or node.get("tagCount")
                    or node.get("count")
                )
                if count is None and isinstance(genre_inner, dict):
                    count = (
                        genre_inner.get("usersCount")
                        or genre_inner.get("tagCount")
                        or genre_inner.get("count")
                        or genre_inner.get("worksCount")
                    )

                _set_shelf(name, count)

        return {
            "status": "success",
            "rating": rating,
            "reviews": reviews,
            "shelves": json.dumps(shelves_dict),
        }

    except Exception as e:
        return {"status": f"parse_error: {str(e)}", "reviews": None, "rating": None, "shelves": None}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--template", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument(
        "--status-log",
        default=None,
        help="Append human-readable progress lines (UTC timestamps) for monitoring (e.g. tail -f).",
    )
    parser.add_argument(
        "--merge-existing-output",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Merge with existing output CSV on book_id, keep='last' (freshest scrape wins).",
    )
    args = parser.parse_args()

    status_fp = None
    if args.status_log:
        os.makedirs(os.path.dirname(args.status_log) or ".", exist_ok=True)
        status_fp = open(args.status_log, "a", encoding="utf-8")

    def status(msg: str) -> None:
        print(msg, flush=True)
        if status_fp:
            status_fp.write(f"{_utc_ts()} {msg}\n")
            status_fp.flush()

    try:
        df = pd.read_csv(args.template)
        results = []
        scraped, failed = 0, 0
        n = len(df)

        status(f"RUN_START template={args.template} output={args.output} books={n}")
        status(f"Starting scrape for {n} titles...")

        scraper = make_scraper()

        for pos, (_, row) in enumerate(df.iterrows(), start=1):
            url = row["goodreads_url"]
            title = str(row["book_title"])
            if len(title) > 70:
                title = title[:67] + "..."

            result = scrape_book_page(scraper, url)

            if result["status"] == "success":
                rev_disp = _format_review_count(result["reviews"])
                line = f"[{pos}/{n}] {title} | SUCCESS ({rev_disp} reviews)"
                scraped += 1
            else:
                line = f"[{pos}/{n}] {title} | FAILED ({result['status']})"
                failed += 1

            status(line)

            results.append({
                **row.to_dict(),
                "reviews_count": result["reviews"],
                "avg_rating": result["rating"],
                "shelves": result["shelves"],
                "date_scraped": str(date.today()),
                "status": result["status"],
            })

            if result["status"] == "rate_limited":
                status("Rate limited — sleeping 30 seconds")
                time.sleep(30)

        out_df = pd.DataFrame(results)
        out_df["book_id"] = out_df["goodreads_url"].map(book_id_from_url)

        if args.merge_existing_output and os.path.isfile(args.output):
            prev = pd.read_csv(args.output)
            if "book_id" not in prev.columns:
                prev["book_id"] = prev["goodreads_url"].map(book_id_from_url)
            out_df = pd.concat([prev, out_df], ignore_index=True)
            out_df = out_df.drop_duplicates(subset=["book_id"], keep="last")

        os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
        out_df.to_csv(args.output, index=False)

        status(f"{'=' * 50}")
        status(f"RUN_END template={args.template} scraped={scraped}/{n} failed={failed}/{n}")
        status(f"Saved to: {args.output}")
    finally:
        if status_fp:
            status_fp.close()
